---
- name: "Docker block"
  block:
    - name: "Check if {{ compose_file_name }} exists in the project directory"
      ansible.builtin.stat:
        path: "{{ compose_project_dir }}/{{ compose_file_name }}"
      register: compose_file_stat

    - name: "Update Docker Compose services (pull images, recreate containers)"
      community.docker.docker_compose_v2:
        project_src: "{{ compose_project_dir }}"
        project_name: "{{ compose_project_name | default(omit) }}"
        state: present
        pull: always
        recreate: always
        remove_orphans: true
        build: false
      register: compose_update_result
      notify: "Show Docker Compose Update Info"
      when: compose_file_stat.stat.exists

  handlers:
    - name: "Show Docker Compose Update Info"
      listen: Show Docker Compose Update Info
      ansible.builtin.debug:
        msg: "Docker Compose update process completed. Review task output for details."
        # You can access detailed output via compose_update_result if needed, e.g.:
        # var: compose_update_result
        # verbosity: 1 # Only show with -v
  vars:
    # --- User Configuration ---
    compose_project_dir: "{{ update_docker_homelab_docker_folder }}"
    # compose_project_name: "my_app_stack"
    compose_file_name: "compose.yaml"
    # --- End User Configuration ---
