---
- name: "Docker block"
  block:
    - name: "Check if {{ compose_file_name }} exists in the project directory"
      ansible.builtin.stat:
        path: "{{ compose_project_dir }}/{{ compose_file_name }}"
      register: compose_file_stat

    - name: "Update Docker Compose services (pull images, recreate containers)"
      community.docker.docker_compose_v2:
        project_src: "{{ compose_project_dir }}"
        project_name: "{{ compose_project_name | default(omit) }}"
        state: present
        pull: always
        recreate: always
        remove_orphans: true
        build: false
      register: compose_update_result
      when: compose_file_stat.stat.exists

  vars:
    compose_project_dir: "{{ update_docker_homelab_docker_folder }}"
    compose_file_name: "compose.yaml"
