---
- name: "Run the equivalent of apt update as a separate step"
  ansible.builtin.apt:
    update_cache: true

- name: "Update all packages to their latest version"
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: "Remove dependencies that are no longer required and purge their configuration files"
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: 'Run the equivalent of apt clean as a separate step'
  ansible.builtin.apt:
    clean: true
