---
- hosts: "all"
  # pre_tasks:
  #   - name: "Ensure required collections from file are installed (run once on control node)"
  #     ansible.builtin.command: "ansible-galaxy collection install -r requirements.yaml"
  #     delegate_to: localhost
  #     run_once: true
  #     changed_when: false
  #     check_mode: false
  #     tags:
  #       - always
  tasks:
    - name: "Add hosts to inventory groups"
      ansible.builtin.add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ hostvars[inventory_hostname].pull_groups }}"
      changed_when: false
      tags:
        - always

- import_playbook: playbook.yml
