---
- hosts: "all"
  tasks:
    - name: "Add hosts to inventory groups"
      ansible.builtin.add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ hostvars[inventory_hostname].pull_groups }}"
      changed_when: false
      tags:
        - always

- import_playbook: playbook.yml
