---
version: '3'

vars:
  PASSWORD_FILE: ~/.config/homelab-pull/password
  PASSWORD_DIR: '{{dir .PASSWORD_FILE}}'
  PASSWORD_LENGTH: 32

tasks:
  lint:
    desc: "Run ansible-lint"
    cmds:
      - ansible-lint local.yml
  reqs:
    desc: "Install or update collections"
    cmds:
      -  "ansible-galaxy collection install -r requirements.yaml --force"
  show-passwd:
    desc: Show the password
    cmds:
      - cat {{ .PASSWORD_FILE }}
  gen-passwd:
    desc: "Generates a random password and saves it to {{.PASSWORD_FILE}}"
    cmds:
      - mkdir -p {{ .PASSWORD_DIR }}
      - openssl rand -base64 {{ .PASSWORD_LENGTH }} > {{.PASSWORD_FILE}}
      - chmod 600 {{ .PASSWORD_FILE }}
      - echo "Password successfully generated and saved to {{ .PASSWORD_FILE }}"
    preconditions:
       - sh: command -v openssl >/dev/null
         msg: "'openssl' command not found. Please install OpenSSL."
  test:
    desc: Run a test Docker container.
    cmds:
      - docker run -it --rm -h "$(uname -n)" debian /bin/bash
    preconditions:
       - sh: command -v docker >/dev/null
         msg: "'docker' command not found. Please install Docker."

  default:
    cmds:
      - task -l
    silent: true
