---
- name: "Get list of files in /var/log/"
  ansible.builtin.find:
    paths: /var/log/
    file_type: file
  register: cleanup

- name: "Delete files in /var/log"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ cleanup.files }}"
  ignore_errors: true
  no_log: true
