---
- name: Get user variables
  ansible.builtin.user:
    name: root
    state: present
  register: user

- name: "Clean tmp"
  ansible.builtin.include_tasks:
    file: "tmp.yaml"
    apply:
      tags:
        - tmp
  tags:
    - always

- name: "Clean cache"
  ansible.builtin.include_tasks:
    file: "cache.yaml"

- name: "Clean logs"
  ansible.builtin.include_tasks:
    file: "logs.yaml"

- name: "Clean apt"
  ansible.builtin.include_tasks:
    file: "apt.yaml"

- name: "Get mount"
  ansible.builtin.set_fact:
    mount: "{{ ansible_mounts | first }}"

- set_fact: disk_usage="{{ mount.size_total - mount.size_available }}"
- set_fact: disk_usage_ratio="{{ disk_usage|float / mount.size_total }}"
# - set_fact: disk_usage_s="{{ (disk_usage|float / 1000000000) | round(1, 'common') }}GB"
- set_fact: disk_usage_s="{{ (disk_usage|float / (1024*1024*1024)) | round(2, 'common') }}GB"
# - set_fact: disk_total_s="{{ (mount.size_total / 1000000000) | round(1, 'common') }}GB"
- set_fact: disk_total_s="{{ (mount.size_total / (1024*1024*1024)) | round(2, 'common') }}GB"
- set_fact: disk_usage_ratio_s="{{ 100 * (disk_usage_ratio|float) | round(2, 'common') }}%"
# - set_fact: disk_limit_ratio_s="{{ (100 * disk_limit|float) |round }}%"

- debug:
    msg: "disk usage {{ disk_usage_s }} of total {{ disk_total_s }} ({{ disk_usage_ratio_s }} {{ disk_usage }} {{ mount.size_available }} {{ mount.size_total }} {{ mount.device }})"
