---
- name: "PVE block"
  block:
    - name: "Check if {{ update_file_name }} exists in the project directory"
      ansible.builtin.stat:
        path: "{{ pve_project_dir }}/{{ update_file_name }}"
      register: update_file_stat
      ignore_errors: true

    - name: "Run update script"
      ansible.builtin.command: "{{ pve_project_dir }}/{{ update_file_name }}"
      register: pve_update_result
      when: update_file_stat.stat.exists
      ignore_errors: true

    - name: "Run update script"
      ansible.builtin.shell:
        cmd: "{{ pve_project_dir }}/{{ update_file_name }}"
        chdir: "{{ pve_project_dir }}"
      ignore_errors: true
      register: run_cheat_script
      when:
        - update_file_stat.exists is defined
        - update_file_stat.stat.exists
  vars:
    pve_project_dir: "{{ update_pve_homelab_pve_folder }}"
    update_file_name: "update.sh"
