---
- name: "AdGuard Home block"
  block:
    - name: "Retrieve DNS rewrites from AdGuard Home"
      ansible.builtin.uri:
        url: "{{ adguard_url }}/control/rewrite/list"
        method: GET
        return_content: true
      register: adguard_rewrites_response
      ignore_errors: true

    - name: "Display DNS rewrites"
      ansible.builtin.debug:
        var: adguard_rewrites_response.json
      when:
        - adguard_rewrites_response.status == 200
        - debug_enabled

    - name: "Perform a boolean check for '{{ domain_to_check }}'"
      ansible.builtin.set_fact:
        is_domain_present: "{{ (adguard_rewrites_response.json | default([]) | selectattr('domain', 'equalto', domain_to_check) | list | length) > 0 }}"
      when: adguard_rewrites_response.status == 200

    - name: "Display boolean check result for '{{ domain_to_check }}'"
      ansible.builtin.debug:
        msg: "Is '{{ domain_to_check }}' present? {{ is_domain_present }}"

  vars:
    adguard_url: "{{ linux_instance_generic_adguard_home_url }}"
    domain_to_check: "{{ adguard_home_rewrite_host }}"
  when:
    - adguard_home_rewrite_host is defined
