---
- name: "Install pipx"
  ansible.builtin.apt:
    name: "pipx"
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"
  register: update_bash_result

- name: "Source bashrc"
  ansible.builtin.shell: "source {{ ansible_env.HOME }}/.bashrc"
  args:
    executable: "/bin/bash"
  when:
    - update_bash_result is defined
    - update_bash_result.changed
  become: false

- name: "Install apprise"
  community.general.pipx:
    name: "apprise"
    state: latest
  become: false
  ignore_errors: true
  
- name: "Create apprise config file"
  ansible.builtin.template:
    src: "apprise.yaml.j2"
    dest: "{{ ansible_env.HOME }}/.config/apprise.yaml"
  become: false
