---
- name: "Install apprise"
  community.general.pipx:
    name: "apprise"
    state: latest
  become: false

- name: "Create apprise config file"
  ansible.builtin.template:
    src: "apprise.yaml.j2"
    dest: "{{ ansible_env.HOME }}/.config/apprise.yaml"
  become: false
