---
- name: "Replace bookworm-security with stable-security in sources.list"
  ansible.builtin.lineinfile:
    path: "/etc/apt/sources.list"
    regexp: '^deb http:\/\/security\.debian\.org\/debian-security bookworm-security main$'
    line: 'deb http://security.debian.org/debian-security stable-security main'
    state: present
    backup: true
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution == "Debian"
    - ansible_lsb.id is not defined or ansible_lsb.id != 'Raspbian'
    - ansible_distribution_codename is defined and ansible_distribution_codename == "bookworm"
    - ansible_facts.file_facts['/etc/apt/sources.list'] is defined and ansible_facts.file_facts['/etc/apt/sources.list'].exists