---
- name: "Change user shell to bash"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "/bin/bash"

# - name: "Update .bash_aliases"
#   ansible.builtin.template:
#     src: .bash_aliases.j2
#     dest: "{{ ansible_env.HOME }}/.bash_aliases"
# 
# - name: "Update .bashrc"
#   ansible.builtin.copy:
#     src: .bashrc
#     dest: "{{ ansible_env.HOME }}/.bashrc"
#   register: update_bash_result

- name: "Replace old hostname with new hostname"
  ansible.builtin.replace:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "xterm-color\\) color_prompt=yes;;$"
    replace: "xterm-color|xterm-256color) color_prompt=yes;;"
  register: update_bash_result

- name: "Source bashrc"
  ansible.builtin.shell: "source {{ ansible_env.HOME }}/.bashrc"
  args:
    executable: "/bin/bash"
  when: update_bash_result.changed
