---
- name: "Change user shell to bash"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "/bin/bash"

- name: "Replace old hostname with new hostname"
  ansible.builtin.replace:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "xterm-color\\) color_prompt=yes;;$"
    replace: "xterm-color|xterm-256color) color_prompt=yes;;"
  register: update_bash_result

- name: "Source bashrc"
  ansible.builtin.shell: "source {{ ansible_env.HOME }}/.bashrc"
  args:
    executable: "/bin/bash"
  when: update_bash_result.changed
