---
- name: "beszel-agent block"
  block:
    - name: "Query GitHub API for latest beszel release"
      ansible.builtin.uri:
        url: "{{ github_api_url }}"
        method: GET
        return_content: true
        body_format: json
        status_code: 200
        headers:
          Accept: "application/vnd.github.v3+json"
          User-Agent: "Ansible-Playbook"
      register: github_release_info
      # Optional: Make task robust against temporary network issues
      retries: 3
      delay: 5
      until: github_release_info.status == 200

    - name: "Extract and store the latest version tag"
      ansible.builtin.set_fact:
        desired_version: "{{ github_release_info.json.tag_name | regex_search(version_regex, '\\1') | first | default('none') }}"
      when:
        - github_release_info.status == 200
        - github_release_info.json is defined

    - name: "Check current version of {{ app_name }}"
      ansible.builtin.command: "{{ app_version_command }}"
      register: version_check_result
      changed_when: false
      failed_when: false

    - name: "Parse current version of {{ app_name }} if installed"
      ansible.builtin.set_fact:
        current_version: "{{ version_check_result.stdout | regex_search(version_regex, '\\1') | first | default('none') }}"
      when: version_check_result.rc == 0

    - name: "Another cheat block"
      block:
        - name: "Show desigred version"
          ansible.builtin.debug:
            msg: "desired_version: {{ desired_version }}\ncurrent_version: {{ current_version }}"
          when: current_version is defined

        - name: "Create beszel agent service file"
          ansible.builtin.template:
            src: beszel-agent.service.j2
            dest: "/etc/systemd/system/beszel-agent.service"

        - name: "Setup update service"
          ansible.builtin.copy:
            src: beszel-agent-update.service
            dest: "/etc/systemd/system/beszel-agent-update.service"

        - name: "Setup timer"
          ansible.builtin.copy:
            src: beszel-agent-update.timer
            dest: "/etc/systemd/system/beszel-agent-update.timer"

        - name: "Just force systemd to reread configs"
          ansible.builtin.systemd_service:
            daemon_reload: true
            name: beszel-agent.service
            enabled: true
            state: started
          ignore_errors: true

        - name: "Enable beszel-agent-update.timer"
          ansible.builtin.systemd_service:
            name: beszel-agent-update.timer
            state: started
            enabled: true
          ignore_errors: true

        - name: "Check if the target URL is reachable"
          ansible.builtin.uri:
            url: "https://installer.l.nicholaswilde.io/henrygd/beszel?as=beszel-agent"
            method: GET
            status_code: 200
            timeout: 5
          register: url_check_result
          ignore_errors: true
          no_log: true

        - name: "Install beszel-agent"
          ansible.builtin.shell: "curl -s https://installer.l.nicholaswilde.io/henrygd/beszel?as=beszel-agent | bash"
          args:
            chdir: "/usr/local/bin"
          when: not url_check_result.failed

        - name: "Install beszel-agent"
          ansible.builtin.shell: "curl -s https://i.jpillora.com/henrygd/beszel?as=beszel-agent | bash"
          args:
            chdir: "/usr/local/bin"
          when: url_check_result.failed

      when:
        - version_check_result.rc != 0 or
          (version_check_result.rc == 0 and
          current_version | default('0.0.0') is version(desired_version, '!='))
          # - current_version | default('none') != desired_version
  vars:
    app_name: "beszel-agent"  # The command name of the application
    repo_name: "beszel"
    owner_name: "henrygd"
    app_version_command: "{{ app_name }} version"
    version_regex: '(\d+\.\d+\.\d+)'
    github_api_url: "https://api.github.com/repos/{{ owner_name }}/{{ repo_name }}/releases/latest"

- name: "Register host with Beszel PocketBase API"
  block:
    - name: "Authenticate with PocketBase and get token"
      ansible.builtin.uri:
        url: "{{ beszel_pocketbase_url }}/api/collections/users/auth-with-password"
        method: POST
        body_format: json
        body:
          identity: "{{ linux_instance_generic_beszel_username }}"
          password: "{{ linux_instance_generic_beszel_password }}"
        return_content: true
        status_code: 200
        validate_certs: false # Consider making this configurable
      register: pocketbase_auth_result
      no_log: true # IMPORTANT: Do not log sensitive data

    - name: "Set PocketBase token fact"
      ansible.builtin.set_fact:
        pocketbase_token: "{{ pocketbase_auth_result.json.token }}"
      when: pocketbase_auth_result.json.token is defined

    - name: "Set PocketBase user id fact"
      ansible.builtin.set_fact:
        pocketbase_user_id: "{{ pocketbase_auth_result.json.record.id }}"
      when: pocketbase_auth_result.json.record.id is defined

    - name: "Debug"
      ansible.builtin.debug:
        var: pocketbase_auth_result
      when:
        - pocketbase_auth_result is defined
        - debug_enabled

    - name: "Check if host is already registered in PocketBase"
      ansible.builtin.uri:
        url: "{{ beszel_pocketbase_url }}/api/collections/systems/records"
        method: GET
        headers:
          Authorization: "Bearer {{ pocketbase_token }}"
        return_content: true
        status_code: 200
        validate_certs: false
        body_format: json
      register: pocketbase_host_check_result
      when: pocketbase_token is defined

    - name: "Extract Device IDs using map filter"
      ansible.builtin.set_fact:
        syncthing_device_ids_map: "{{ pocketbase_host_check_result.json.items | map(attribute='id') | list }}"
      when: pocketbase_host_check_result.json is defined

    - name: "Display extracted Device IDs"
      ansible.builtin.debug:
        var: syncthing_device_ids_map
      when:
        - syncthing_device_ids_map is defined
        - debug_enabled
  
    # - name: "Debug"
    #   ansible.builtin.debug:
    #     var: pocketbase_host_check_result
    #   when: pocketbase_host_check_result is defined

    - name: "Set host exists fact"
      ansible.builtin.set_fact:
        pocketbase_host_exists: "{{ pocketbase_host_check_result.json.items | selectattr('host', 'equalto', '192.168.2.142') | list | length > 0 }}"
      when: pocketbase_token is defined and pocketbase_host_check_result.json is defined

    - name: "Debug"
      ansible.builtin.debug:
        var: pocketbase_host_exists
      when:
        - pocketbase_host_exists is defined
        - debug_enabled

    - name: "Register host in PocketBase if it does not exist"
      ansible.builtin.uri:
        url: "{{ beszel_pocketbase_url }}/api/collections/systems/records"
        method: POST
        headers:
          Authorization: "Bearer {{ pocketbase_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ inventory_hostname }}"
          host: "{{ ansible_default_ipv4.address }}"
          port: '45876'
          status: "up"
          users:
            - "{{ pocketbase_user_id }}"
        status_code: [200, 201]
        validate_certs: false
      when:
        - pocketbase_token is defined
        - not pocketbase_host_exists
        - pocketbase_user_id is defined
      register: pocketbase_host_add_result

    - name: "Display PocketBase registration result"
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} registered in PocketBase."
      when: pocketbase_host_add_result.changed
  when:
    - beszel_pocketbase_url is defined
    - beszel_pocketbase_url != "YOUR_POCKETBASE_URL_HERE"
    - linux_instance_generic_beszel_username is defined
    - linux_instance_generic_beszel_username != "YOUR_BESZEL_USERNAME_HERE"
    - linux_instance_generic_beszel_password is defined
    - linux_instance_generic_beszel_password != "YOUR_BESZEL_PASSWORD_HERE"
  ignore_errors:  true # Optional: depending on how critical this is

  vars:
    app_name: "beszel-agent"  # The command name of the application
    repo_name: "beszel"
    owner_name: "henrygd"
    app_version_command: "{{ app_name }} version"
    version_regex: '(\d+\.\d+\.\d+)'
    github_api_url: "https://api.github.com/repos/{{ owner_name }}/{{ repo_name }}/releases/latest"
