---
- name: cheat block
  block:
    - name: Create cheat directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/cheat/"
        state: directory
        
    - name: Download cheat config file
      ansible.builtin.get_url:
        url: https://github.com/nicholaswilde/dotfiles2/raw/refs/heads/main/.config/cheat/conf.yml
        dest: "{{ ansible_env.HOME }}/.config/cheat/conf.yml"

    - name: Download cheat config file
      ansible.builtin.uri:
        url: https://installer.l.nicholaswilde.io/cheat/cheat?type=script
        return_content: true
      register: this

    - name: Write install script to file
      ansible.builtin.copy:
        content: "{{ this.content }}"
        dest: "/tmp/cheat.sh"
        mode: 0755

    - name: Execute the remote bash script using shell 
      ansible.builtin.shell:
        cmd: "/tmp/cheat.sh"
        chdir: "/tmp/"

    - name: Move cheat
      ansible.builtin.copy:
        src: "/tmp/cheat"
        dest: "/usr/local/bin/cheat"
        remote_src: true
        mode: 0755

    # - name: Cleanup
