---
- name: "Download script for {{ item.destFile }}"
  ansible.builtin.uri:
    url: "https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/etc/{{ item.sourceFile }}?format=TEXT"
    return_content: true
  register: this

- name: "Write script to file for {{ item.destFile }}"
  ansible.builtin.copy:
    content: "{{ this.content | b64decode }}"
    dest: "/usr/local/bin/{{ item.destFile }}"
    mode: "0755"
