---
- name: "Download {{ item.destFile }} script"
  ansible.builtin.uri:
    url: "https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/etc/{{ item.sourceFile }}?format=TEXT"
    return_content: true
  register: this

- name: "Write {{ item.destFile }} script to file"
  ansible.builtin.copy:
    content: "{{ this.content | b64decode }}"
    dest: "/usr/local/bin/{{ item.destFile }}"
    mode: 0755

# - name: "Download show-file script"
#   ansible.builtin.uri:
#     url: "https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/etc/hterm-show-file.sh?format=TEXT"
#     return_content: true
#   register: this
# 
# - name: "Write show-file script to file"
#   ansible.builtin.copy:
#     content: "{{ this.content | b64decode }}"
#     dest: "/usr/local/bin/show-file"
#     mode: 0755
# 
# - name: "Download copy script"
#   ansible.builtin.uri:
#     url: "https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/etc/osc52.sh?format=TEXT"
#     return_content: true
#   register: this
# 
# - name: "Write copy script to file"
#   ansible.builtin.copy:
#     content: "{{ this.content | b64decode }}"
#     dest: "/usr/local/bin/copy"
#     mode: 0755
