---
- name: "git checkout dotfiles repo"
  ansible.builtin.git:
    repo: "{{ linux_instance_generic_dotfiles_repo }}"
    dest: "{{ ansible_env.HOME }}/{{ linux_instance_generic_dotfiles_folder }}"
    accept_hostkey: true
    force: true
  become: false

- name: "Ensure stow is installed"
  ansible.builtin.package:
    name: stow
    state: present
  become: true

- name: "Cleanup files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_env.HOME }}/.bash_aliases"
    - "{{ ansible_env.HOME }}/.bash_exports"
    - "{{ ansible_env.HOME }}/.bashrc"
    - "{{ ansible_env.HOME }}/.gitconfig"
  ignore_errors: true

- name: "Stow dotfile configurations"
  ansible.builtin.command:
    cmd: "stow -t {{ ansible_env.HOME }} ."
    chdir: "{{ ansible_env.HOME }}/{{ linux_instance_generic_dotfiles_folder }}"
  register: stow_result
  changed_when: "'LINK' in stow_result.stdout"
  become: false
