---
- name: Git user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: " {{ linux_instance_generic_git_email }}"
  become: false

- name: Git user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "nιcнolaѕ wιlde"
  become: false

- name: Git init.defaultBranch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
  become: false

- name: Git init.rebase
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: false
  become: false

- name: Git user.signingkey
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ linux_instance_generic_git_signing_key }}"
  become: false

- name: Git commit.gpgsign
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: true
  become: false

- name: git checkout homelab repo
  ansible.builtin.git:
    repo: "{{ linux_instance_generic_git_repo }}"
    dest: "{{ ansible_env.HOME }}/{{ linux_instance_generic_git_folder }}"
    accept_hostkey: true
    force: true
  become: false
