---
- name: Copy gpg files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: "/home/nicholas/{{ setup_gpg_files.private }}"
      dest: "{{ user.home }}/{{ setup_gpg_files.private }}"
    - src: "/home/nicholas/{{ setup_gpg_files.public }}"
      dest: "{{ user.home }}/{{ setup_gpg_files.public }}"

- name: Import gpg files
  ansible.builtin.command: >
    gpg --import {{ item.dest }}
  loop:
    - dest: "{{ user.home }}/{{ setup_gpg_files.public }}"
    - dest: "{{ user.home }}/{{ setup_gpg_files.private }}"

- name: Cleanup gpp files
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: absent
  loop:
    - dest: "{{ user.home }}/{{ setup_gpg_files.public }}"
    - dest: "{{ user.home }}/{{ setup_gpg_files.private }}"
