---
- name: Setup reprepro
  ansible.builtin.include_tasks: reprepro.yaml

- name: Install stuff
  ansible.builtin.include_tasks: install.yaml

- name: Setup SSH
  ansible.builtin.include_tasks: ssh.yaml
