---
- name: Download dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/nicholaswilde/dotfiles2.git'
    dest: '/tmp/dotfiles'
  
- name: Create .config directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    # mode: '0755'

- name: Copy micro config files over
  ansible.builtin.copy:
    src: "/tmp/dotfiles/.config/micro"
    dest: "{{ ansible_env.HOME }}/.config"
    remote_src: true
