---
- name: "Check if the flag file '{{ file_to_check }}' exists"
  ansible.builtin.stat:
    path: "/home/nicholas/.config/sops/age/"
  delegate_to: localhost
  run_once: true
  register: flag_folder_status

- name: Copy age keys
  ansible.builtin.copy:
    src: "/home/nicholas/.config/sops/age/"
    dest: "{{ ansible_env.HOME }}/.config/sops/age/"
  ignore_errors: true
  when: flag_folder_status.stat.exists
