---
- name: "Create directory if it doesn't exist"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/sops/age/"
    state: directory

- name: "Write SOPS age keys"
  ansible.builtin.copy:
    content: "{{ age_key }}"
    dest: "{{ ansible_env.HOME }}/.config/sops/age/keys.txt"
  ignore_errors: true
  when: flag_folder_status.stat.exists
