---
- name: "Ensure .ssh directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'
  become: false

- name: "Fetch SSH public keys from GitHub"
  ansible.builtin.uri:
    url: "{{ linux_instance_generic_ssh_public_key_url }}"
    method: GET
    return_content: true
  register: github_keys
  become: false
  changed_when: false

- name: "Ensure authorized_keys file exists and has correct permissions"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  become: false

- name: "Add fetched SSH keys to authorized_keys"
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
    state: present
    path: "{{ ansible_env.HOME }}/.ssh/authorized_keys" # Explicitly provide path for clarity
    manage_dir: false # We are managing the .ssh directory separately
  loop: "{{ github_keys.content.splitlines() }}"
  when:
    - github_keys.status == 200
    - item | trim != "" # Avoid adding empty lines
    - not item.startswith('#') # Avoid adding comments
  become: false # Should not need become if running as the user
