---
- name: "Run tmux Block"
  block:
    - name: "Create .config directory if it does not exist"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory
      become: false

    - name: "Create tpm directory if it does not exist"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
        state: directory
      become: false
      
    - name: "Install tmux plugins manager (tpm)"
      ansible.builtin.git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
        accept_hostkey: true
        force: true
      become: false
      register: tpm_result
      ignore_errors: true

    # - name: "Reload tmux"
    #   ansible.builtin.command: "tmux source {{ ansible_env.HOME }}/.config/tmux/tmux.conf"
    #   become: false
    #   when: tpm_result.changed
      
    - name: "Install tmux plugins"
      ansible.builtin.command: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins"
      environment:
        TMUX_PLUGIN_MANAGER_PATH: "{{ ansible_env.HOME }}/.tmux/plugins/"
      when: tpm_result.changed
      become: false
      ignore_errors: true
  vars:
    TMUX_PLUGIN_MGR_PATH: "{{ ansible_env.HOME }}/.tmux/plugins/"
