---
- name: "Run tmux Block"
  # vars:
    # TMUX_PLUGIN_MGR_PATH: "{{ ansible_env.HOME }}/.tmux/plugins/"
  block:
    - name: "Create .config directory if it does not exist"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory

    - name: "Create tpm directory if it does not exist"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
        state: directory

    - name: "Install tmux plugins manager (tpm)"
      ansible.builtin.git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
        accept_hostkey: true
        force: true
      register: tpm_result
      ignore_errors: true

    - name: "Check if tmux server is running for user {{ ansible_user }}"
      ansible.builtin.command: "pgrep -u {{ ansible_user }} tmux"
      register: tmux_process_check
      changed_when: false
      failed_when: false

    - name: "Reload tmux"
      ansible.builtin.command: "tmux source {{ ansible_env.HOME }}/.config/tmux/tmux.conf"
      when:
        - tpm_result.changed
        - tmux_process_check.rc == 0

    - name: "Install tmux plugins"
      ansible.builtin.command: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins"
      environment:
        TMUX_PLUGIN_MANAGER_PATH: "{{ ansible_env.HOME }}/.tmux/plugins/"
      when: tpm_result.changed
      ignore_errors: true
