---
- name: Install units for homelab-pull
  ansible.builtin.template:
    dest: "/etc/systemd/system/{{ item | regex_replace('\\.j2$', '') }}"
    src: "{{ item }}"
  loop:
    - homelab-pull.service.j2
    - homelab-pull.timer.j2

- name: Enable homelab-pull timer
  ansible.builtin.service:
    name: homelab-pull.timer
    state: started
    enabled: true
    daemon_reload: true
