---
- name: Install units for ansible-pull
  ansible.builtin.template:
    dest: /etc/systemd/system
    src: "{{ item }}"
  loop:
    - ansible-pull.service
    - ansible-pull.timer

- name: Enable ansible-pull timer
  ansible.builtin.service:
    name: ansible-pull.timer
    state: started
    enabled: true
